# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ABOUT(object):
    def setupUi(self, ABOUT):
        ABOUT.setObjectName("ABOUT")
        ABOUT.resize(616, 307)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ABOUT.setWindowIcon(icon)
        ABOUT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(ABOUT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ABOUT)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 170, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(ABOUT)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Pics/WK.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(ABOUT)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Pics/Bow.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(ABOUT)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Pics/Logo_3.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ABOUT)
        QtCore.QMetaObject.connectSlotsByName(ABOUT)

    def retranslateUi(self, ABOUT):
        _translate = QtCore.QCoreApplication.translate
        ABOUT.setWindowTitle(_translate("ABOUT", "About"))
        self.label.setText(_translate("ABOUT", "It is a Fantasy game where you create a virtual team of real cricket players and \n"
"score points depending on how your chosen players perform in real life matches.\n"
"To win a tournament,you must try and get the maximum points and the  No. 1 \n"
"rank amongst other participants.\n"
"\n"
"\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ABOUT = QtWidgets.QDialog()
    ui = Ui_ABOUT()
    ui.setupUi(ABOUT)
    ABOUT.show()
    sys.exit(app.exec_())
