# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error_Message(object):
    def setupUi(self, Error_Message):
        Error_Message.setObjectName("Error_Message")
        Error_Message.resize(488, 239)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Error_Message.setWindowIcon(icon)
        Error_Message.setWindowOpacity(0.8)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Error_Message)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Error_Message)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Oh_No = QtWidgets.QLabel(self.frame)
        self.Oh_No.setGeometry(QtCore.QRect(20, 10, 191, 201))
        self.Oh_No.setText("")
        self.Oh_No.setPixmap(QtGui.QPixmap("Pics/Oh_No.png"))
        self.Oh_No.setScaledContents(True)
        self.Oh_No.setObjectName("Oh_No")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Error_Message)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Oh_No_Message = QtWidgets.QLabel(self.frame_2)
        self.Oh_No_Message.setGeometry(QtCore.QRect(10, 10, 211, 161))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Oh_No_Message.setFont(font)
        self.Oh_No_Message.setText("")
        self.Oh_No_Message.setPixmap(QtGui.QPixmap("Pics/Oh_No.png"))
        self.Oh_No_Message.setObjectName("Oh_No_Message")
        self.OKEr_PB = QtWidgets.QPushButton(self.frame_2)
        self.OKEr_PB.setGeometry(QtCore.QRect(90, 190, 75, 23))
        self.OKEr_PB.setStyleSheet("font: 75 8pt \"Comic Sans MS\";")
        self.OKEr_PB.setObjectName("OKEr_PB")
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Error_Message)
        QtCore.QMetaObject.connectSlotsByName(Error_Message)

    def retranslateUi(self, Error_Message):
        _translate = QtCore.QCoreApplication.translate
        Error_Message.setWindowTitle(_translate("Error_Message", "Snap!!"))
        self.OKEr_PB.setText(_translate("Error_Message", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error_Message = QtWidgets.QDialog()
    ui = Ui_Error_Message()
    ui.setupUi(Error_Message)
    Error_Message.show()
    sys.exit(app.exec_())
